#!/bin/bash

#
# Configuration
#

NAME=windows7
TMP_FOLDER=tmp-$NAME

#
# Script
#

cd `dirname $0`
CDIR=$(pwd)

if [ -a rootfs/$NAME.* ]; then
  rm -f rootfs/$NAME.*
  rm -f rootfs_$NAME
  rm -dfr $TMP_FOLDER
fi

mkdir -p $TMP_FOLDER
cd $TMP_FOLDER
#wget https://az412801.vo.msecnd.net/vhd/VMBuild_20141027/VirtualBox/IE10/Windows/IE10.Win7.For.Windows.VirtualBox.zip
wget https://az412801.vo.msecnd.net/vhd/VMBuild_20141027/VMware/IE10/Windows/IE10.Win7.For.Windows.VMware.zip
unzip *.zip
mkdir -p $CDIR/rootfs
cd $CDIR
mv $TMP_FOLDER/*.vmdk rootfs/$NAME.vmdk
ln -s rootfs/$NAME.vmdk rootfs_$NAME
rm -rf $TMP_FOLDER
