#!/bin/bash

#
# Configuration
#

NAME=kali
TMP_FOLDER=tmp-$NAME

#
# Script
#

cd `dirname $0`
CDIR=$(pwd)

if [ -a rootfs/$NAME.* ]; then
  rm -f rootfs/$NAME.*
  rm -f rootfs_$NAME
  rm -dfr $TMP_FOLDER
fi

mkdir -p $TMP_FOLDER
cd $TMP_FOLDER
vnx_download_rootfs -r vnx_rootfs_kvm_kali64-2016.2-v025.qcow2.bz2
mkdir -p $CDIR/rootfs
cd $CDIR
mv $TMP_FOLDER/*.qcow2 rootfs/$NAME.qcow2
ln -s rootfs/$NAME.qcow2 rootfs_$NAME
rm -rf $TMP_FOLDER
